# Uncomment this line to define a global platform for your project
# platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Prescribe' do
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'BRYXBanner'
end

